server:
 port: 8080
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: APIGateWayService


 cloud:
  gateway:
   routes:
    - id: jwtModule
      uri: http://localhost:8081/
      predicates:
      - Path=/api/jwt/**
    - id: profileModule
      uri: http://localhost:8082/
      predicates:
      - Path=/api/pro/**
    - id: trainingModule
      uri: http://localhost:8083/
      predicates:
      - Path=/api/train/** 
    - id: trainingModule
      uri: http://localhost:8084/
      predicates:
      - Path=/api/ftrain/**    
    - id: assesmentModule
      uri: http://localhost:8085/
      predicates:
      - Path=/api/assesment/**    
   globalcors:
         cors-configurations:
                    '[/**]':
                        allowedOrigins : "http://localhost:3000"
                        allowCredentials: true
                        allowedHeaders : 
                                - content-type
                                - Authorization
                        allowedMethods :
                                 - GET
                                 - POST
                                 - PUT
                                 - DELETE     
      
      
logging:
  file: 
    path: /my-logs/app.log
    name: log.txt      